### ISSUE TITLE
Results are not consistent in CIS audit output

### ISSUE THREAD

**Issue by GhuulCZ** [ansible-lockdown/UBUNTU22-CIS-Audit#12]
**Describe the Issue**
Some checks are not reported because of how goss works - see https://github.com/goss-org/goss/issues/743

**Expected Behavior**
I'm not sure if there is anything you can do on your side except completely redo some of the checks to avoid overlapping names

**Actual Behavior**
goss produces output with different checks on different machines.

**Control(s) Affected**
have not time to go through all but eg. in section 1.4 and 1.6 the checks that are testing same grub.cfg file are overlapping

**Environment (please complete the following information):**
- branch being used: I have seen this issue in eg main and benchmark-v1.0.0
- goss v0.3.23

**Possible Solution**
If we do not want to consolidate the checks (and I dont believe thats a good idea) then only workaround I was able to come up with is to run goss independently for each section(s) we know are overlapping and combine all the results

**Comment by uk-bolly** [comment]
hi @GhuulCZ 

Thank you for taking the time to raise this issue, i believe this has now been addressed for both the devel and the benchmark branches. We have moved to the newer version of goss which enables this tests to take place.

Please let us know if you see anything else that is not as expected.

many thanks

uk-bolly
