### ISSUE TITLE
Incorrect check

### ISSUE THREAD

**Issue by berdugonoa** [ansible-lockdown/UBUNTU22-CIS-Audit#13]
In 'cis-5.2.2 | Ensure sudo commands use pty | Config' there is an error .

This check is a bad check since in is not possible to get that output from that command (the regex expected does not match the one requested) therefore it will always fail.

Since the exec command is:
"grep -Ei "^use_pty" /etc/sudoers"
while the expected output is:
"/^Defaults.*\suse_pty/"
it cannot pass.

The expected behaviour will be to use a regex that can match the the expected output
for axample- "/^Defaults.*\suse_pty/"

This affects the trust in the UBUNTU-CIS-Audit testing.

- branch being used: [e.g. devel] also in main
- Ansible Version: [e.g. 2.10]
- Host Python Version: [e.g. Python 3.7.6]
- Ansible Server Python Version: [e.g. Python 3.7.6]

**Comment by uk-bolly** [comment]
hi @berdugonoa 

Thank you for taking the time to raise this issue, I believe this has been addressed in the devel or benchmark branch.
Please let us know if this is not the case.

many thanks

uk-bolly
