### ISSUE TITLE
Extra or: in section_6/cis_6.2/cis_6.2.3.yml

### ISSUE THREAD

**Issue by WannaBeGeekster** [ansible-lockdown/UBUNTU22-CIS-Audit#24]
**Describe the Issue**
Error: could not read json data in UBUNTU22-CIS-Audit/section_6/cis_6.2/cis_6.2.3.yml: yaml: unmarshal errors:
  line 8: mapping key "or" already defined at line 7

**Expected Behavior**
An error should not be thrown.

**Actual Behavior**
The error message above is pretty obviuos.

**Possible Solution**
Remove the extra or: in the file.

**Comment by uk-bolly** [comment]
hi @WannaBeGeekster 

Thank you for taking the time to raise this issue,
I believe you are using the main branch?
With CIS changing the controls and updating we run audit in a branch name convention with the version of the benchamrk you wish to test with.

Ideally you should be using the benchmark branch which will give you the latest tests for the version you want to run this only has one release at the moment so i would suggest the branch
```benchmark-v1.0.0```

This will give you the latest stable release for that version of the benchmark.
We are using devel as the latest update in general so the main branch is not really used ( this could be an improvment to remove this branch)

I hope that helps

thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @WannaBeGeekster 

I can see this issue has ben open for a while, i hope that the answer given previously helped. I will close this issue, pleasefeel free to reopen if this is still not working as expected.

many thanks

uk-bolly
