### ISSUE TITLE
The CIS 4.1.3.2 check is not working

### ISSUE THREAD

**Issue by wh-zfy** [ansible-lockdown/UBUNTU22-CIS-Audit#30]
**Describe the Issue**
The auditd rule for "4.1.3.2 | Ensure actions as another user are always logged | Config" is applied but the check shows it as failed.

**Expected Behavior**
Show as passed.

**Actual Behavior**
Shows as failed.

**Control(s) Affected**
CIS 4.1.3.2

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.16.7
- Host Python Version: 3.12.3
- Ansible Server Python Version: 3.10.12

**Additional Notes**
The key of the auditd rule was changed from "actions" to "user_emulation" in [https://github.com/ansible-lockdown/UBUNTU22-CIS/blob/devel/templates/audit/99_auditd.rules.j2](url) and with commit [https://github.com/ansible-lockdown/UBUNTU22-CIS-Audit/commit/f14547455befe3a6b6db3f2df91aec456a4b9816](url) the key was adapted in the expected output.
The key was not updated in the grep commands to get the corresponding rules `grep actions /etc/audit/rules.d/*.rules` and `auditctl -l | grep actions`.

**Possible Solution**
Update the key used in the grep command and probably also an adjustment of the expected output is needed

**Comment by uk-bolly** [comment]
hi @wh-zfy 

Thank you for this a great catch, i've raised the PR for this issue already, to be merged.

thanks

uk-bolly

**Comment by wh-zfy** [comment]
Hi, I did try the PR and it now finds the rules but the output still does not match with what gets set by Ansible Lockdown UBUNTU22-CIS.

I did also look at UBUNTU22-CIS devel and main as also UBUNTU22-CIS-Audit devel and benchmark-v1.0.0 and didn't notice any differences in the relevant files, so this should affect all versions.

The Ansible role sets:
```
-a always,exit -F arch=b64 -C euid!=uid -F auid!=unset -S execve -k user_emulation
-a always,exit -F arch=b32 -C euid!=uid -F auid!=unset -S execve -k user_emulation
```

When I run `grep user_emulation /etc/audit/rules.d/*.rules` on a system that had the Ansible role applied the output is:
```
/etc/audit/rules.d/99_auditd.rules:-a always,exit -F arch=b64 -C euid!=uid -F auid!=unset -S execve -k user_emulation
/etc/audit/rules.d/99_auditd.rules:-a always,exit -F arch=b32 -C euid!=uid -F auid!=unset -S execve -k user_emulation
```

The output is then matched against:
```
    stdout:
    - '/-a always,exit -F arch=b64 -C euid!=uid -F euid=0 -F auid>=1000 -F auid!=(unset|4294967295|-1) -S execve -k user_emulation/'
    - '/-a always,exit -F arch=b32 -C euid!=uid -F euid=0 -F auid>=1000 -F auid!=(unset|4294967295|-1) -S execve -k user_emulation/'
```

The grep output is exactly what is given in the CIS benchmark as output, but it isn't matched by the check. As I understand, it should also literally match this text.

The check for the loaded rules would then also need an update.

**Comment by uk-bolly** [comment]
hi @wh-zfy 

Thats my fault mean to raise as draft to complete today, as i spotted a couple of other things to address too.
The approvers are in contact with each other, so this was held back. The readme has also been updated to explain how the branches work.
It will be merged to devel hopefully today and the benchmark branch also updated

thanks again

uk-bolly

**Comment by uk-bolly** [comment]
hi @wh-zfy 

These fixed have now been merged into both the benchmark branch and the devel branch.

I will close this issue. Please feel free to open if this is not working as expected.

many thanks

uk-bolly
