### ISSUE TITLE
Audit issue on the CIS recommandation 1.6.1.3 

### ISSUE THREAD

**Issue by Rafouf69** [ansible-lockdown/UBUNTU22-CIS-Audit#34]
**Describe the Issue**

When launching an audit, it indicates that the control 1.6.1.3 is failing. While doing my own analysis based on the resource provided in the pdf document _CIS_Ubuntu_Linux_22.04_LTS_Benchmark_v2.0.0_, it seems that the test should not fail.

From the CIS benchmark:

> Review output and ensure that profiles are loaded, and in either enforce or complain 
mode:

```
$ apparmor_status | grep 'profiles are loaded'
19 profiles are loaded.

$ apparmor_status | grep 'profiles are in enforce mode.'
18 profiles are in enforce mode.

$ apparmor_status | grep 'profiles are in complain mode.'
1 profiles are in complain mode.
```

**Expected Behavior**
Successful audit.

**Actual Behavior**
The test is failing.

**Control(s) Affected**
CIS 1.6.1.3

**Environment (please complete the following information):**

- branch being used: devel
Environment (please complete the following information):

branch being used: devel
Ansible Version: 2.14.11
Host Python Version: 3.10.12 
Ansible Server Python Version: 3.10.12

**Possible Solution**

Instead of this command:

```
LOADED=`apparmor_status | grep 'profiles are loaded' | awk '{print $1}'` && ENFORCE=`apparmor_status | grep 'profiles are in enforce mode.' | awk '{print $1}'` && COMPLAIN=`apparmor_status | grep 'profiles are in complain mode.' | awk '{print $1}'` && if [ $((LOADED + COMPLAIN)) != "$ENFORCE" ]; then echo "Profiles Error";fi
```

We should probably invert `ENFORCE` and `LOADED`:

```
LOADED=`apparmor_status | grep 'profiles are loaded' | awk '{print $1}'` && ENFORCE=`apparmor_status | grep 'profiles are in enforce mode.' | awk '{print $1}'` && COMPLAIN=`apparmor_status | grep 'profiles are in complain mode.' | awk '{print $1}'` && if [ $((ENFORCE + COMPLAIN)) != "$LOADED " ]; then echo "Profiles Error";fi
```

**Comment by uk-bolly** [comment]
hi @Rafouf69 

Thank you for raising this issue and supplying the fix. This should now be merged to the relevant branch for the benchmark version.

Kindest regards

uk-bolly
