### ISSUE TITLE
Wrong object to test and result in 1.1.24

### ISSUE THREAD

**Issue by Iril** [ansible-lockdown/UBUNTU22-CIS-Audit#5]
It seems this test is still looking for cramfs and /bin/true instead of /bin/false

https://github.com/ansible-lockdown/UBUNTU22-CIS-Audit/blob/main/section_1/cis_1.1/cis_1.1.24.yml

Is this correct ?

**Comment by uk-bolly** [comment]
hi @Iril 

Apologies for the delay, i believe this was resolved some time ago and i am looking through the branches to see where this may have occurred.
The control itself asks for /bin/true this means when the file is run the install runs it gets a return code of 0 with a bin/false it would fail and error during loading module.

hope this makes sense

kindest regards

uk-bolly
