### ISSUE TITLE
Ubuntu 22.04 (1.0.0) benchmark released

### ISSUE THREAD

**Issue by modem7** [ansible-lockdown/UBUNTU22-CIS-Audit#6]
Heya,

Thank you very much for your work!

Just an FYI in case you weren't aware, it looks like the 22.04 benchmark has been [released](https://www.cisecurity.org/benchmark/ubuntu_linux) (1.0.0), unsure if anything needs updating.

Thanks again!

**Comment by uk-bolly** [comment]
Hi @modem7 

I have been working on this is in the background and ready for the initial release to devel for both audit and remediate. We generally leave it there pending feedback for a couple of weeks before pushing to main.

For the audit the branches are all labeled with the benchmark version e.g. benchmark_v1.0.0

Thank you for the feedback feel free to join the discord community aswell at https://discord.io/ansible-lockdown

regards

uk-bolly

**Comment by modem7** [comment]
Thank you very much!

The work is sincerely appreciated!

**Comment by uk-bolly** [comment]
All sorted as per ubuntu22-cis

Thanks again @modem7 

uk-bolly
